import React, { useEffect, useState } from "react";
import OtpInput from "react-otp-input";
import { useNavigate } from "react-router-dom";

// Import axiosInstance for authorized connection with API
import axiosInstance from "../utils/axiosInstance";

const OtpValidator = ({ otpToken, id }) => {
  // Use "navigate" to link programatically to another route
  const navigate = useNavigate();
  const [errorMsg, setErrorMsg] = useState("");
  const [otpValue, setotpValue] = useState("");
  console.log("id: ", id);
  const handleVerify = async (e) => {
    e.preventDefault();
    if (otpToken == otpValue) {
      const res = await axiosInstance.get(
        `http://localhost:4000/api/accounts/getUser?id=${id}`
      );
      const user = res?.data?.user;
      console.log("user: ", res?.data);
      localStorage.setItem("user", JSON.stringify(user));
      navigate("/");
    } else {
      setErrorMsg("Incorrect OTP");
    }
  };
  return (
    <div className="SignIn">
      <section className="max-w-3xl mt-20 p-8 mx-auto bg-white rounded-md shadow-md text-lg flex flex-col space-y-6">
        <div className="text-center">
          Please enter the One Time Password (OTP) generated by your Microsoft
          Authenticator App.
        </div>
        <div className="mx-auto">
          <OtpInput
            value={otpValue}
            onChange={(newValue) => setotpValue(newValue)}
            numInputs={6}
            separator={<span>{"  "}</span>}
            inputStyle={{
              border: "solid 1px grey",
              margin: "0 10px",
              borderRadius: "5px",
              width: "50px",
              height: "50px",
            }}
          />
        </div>
        <div className="mx-auto w-60">
          <p className="text-red-800">{errorMsg}</p>
        </div>
        <div className="mx-auto w-60">
          <button
            onClick={(e) => handleVerify(e)}
            className="px-6 w-full py-4 font-bold leading-5 text-white transition-colors duration-200 transform bg-green-600 rounded-md hover:bg-green-700 focus:outline-none focus:bg-green-700"
          >
            Verify
          </button>
        </div>
      </section>
    </div>
  );
};

export default OtpValidator;
